version: '3.1'

services:
 app:
  image: "docker-spring-boot-postgres:latest"
  build:
   context: .
  container_name: app
  depends_on:
   - postgresdb
  environment:
   - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/postgres
   - SPRING_DATASOURCE_USERNAME=postgres
   - SPRING_DATASOURCE_PASSWORD=password123
   - SPRING_JPA_HIBERNATE_DDL_AUTO=update
 
 postgresdb:
  image: "postgres:latest"
  container_name: postgresdb
  restart: always
  ports: 
   - "9000:5432"
  environment:
   POSTGRES_USERNAME: postgres
   POSTGRES_PASSWORD: password123
   POSTGRES_DB: ecommerce